apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-tempo-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo.monitoring:3200
        isDefault: false
        jsonData:
          tracesToMetrics:
            datasourceUid: prometheus
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            tags:
              - key: service.name
                value: service
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          tracesToLogs:
            datasourceUid: loki
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false
            tags:
              - key: service.name
                value: service_name
          lokiSearch:
            datasourceUid: loki
